services:
  providence:
    container_name: ca_app
    build:
      context: .
      args:
        APACHE_RUN_USER: ca-www-data
        APACHE_RUN_GROUP: ca-www-data
    env_file:
      - .docker-compose_providence.env
    volumes:
      - ./ucla_providence:/var/www/html
    ports:
      - "8090:80"
    depends_on:
      - db

  db:
    container_name: ca_db
    image: mysql:8.0
    command: --character-set-server=UTF8MB4 --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --log_bin_trust_function_creators=1
    ports:
      - "3306:3306"
    env_file:
      - .docker-compose_db.env
    healthcheck:
      test: ["CMD-SHELL", "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SHOW DATABASES;'"]
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
